services:
  flask:
    build: .
    container_name: flask-app
    env_file: .env
    depends_on:
      - db
    working_dir: /app
    command: python app.py
    ports:
      - "5000:5000"

  db:
    image: postgres:16
    container_name: postgres-db
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

volumes:
  pgdata:
