- name: Create certs directory
  file:
    path: "{{ certs_dir }}"
    state: directory
    mode: '0755'

- name: Generate private key and self-signed certificate
  become: true
  command: >
    sudo openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout {{ certs_dir }}/nginx.key
    -out {{ certs_dir }}/nginx.crt
    -subj "/C=RU/ST=MSK/L=Moscow/O=Dev/CN=localhost"
  args:
    creates: "{{ certs_dir }}/nginx.crt"
