- name: Create destination directory
  file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'

- name: Copy project files to target location excluding nginx/certs and ansible
  become: yes
  ansible.builtin.shell: >
    rsync -a --exclude='nginx/certs' --exclude='ansible' /home/maksim/myflaskapp/ {{ dest_dir }}/
